version: '3.8'


volumes:
  release:
    external: true
    name: release

services:
  # MySQL 서비스
  mysql:
    container_name: release-DB
    image: mysql:latest
    restart: always
    volumes:
      - release:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ehddn0930
      MYSQL_DATABASE: Heungkuk
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    networks:
      - app-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  

  # Spring Boot 서비스
  spring-boot:
    build:
      context: ./API-Server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8080"
      
    depends_on:
      - mysql
    networks:
      - app-network

  # Next.js (React) 서비스
  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - spring-boot
    networks:
      - app-network

networks:
  app-network:
    driver: bridge